#ifndef HANGMAN_STATEIDENTIFIERS_HPP
#define HANGMAN_STATEIDENTIFIERS_HPP

namespace States {
  enum ID {
    NONE,
    TITLE,
    GAME,
    PAUSE,
    GAME_OVER,
    GAME_OVER_WIN,
  };
}

#endif //HANGMAN_STATEIDENTIFIERS_HPP